mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir

# Force Dovecot mail processes to use vmail identity for file access/creation.
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
last_valid_uid = 5000

namespace inbox {
  inbox = yes
}
